title: title
description: YOUR DESCRIPTION
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll/layout
  - jekyll-include-cache
# Navigation
# List links that should appear in the site sidebar here
navigation:
  - text: Documentation
    internal: true
    url: ./docs

collections:
  docs:
    output: true